handler: puppet
id: 'tweaks'
input:
  ip:
    schema: str!
    value: ''
  ssh_key:
    schema: str!
    value: ''
  ssh_user:
    schema: str!
    value: ''
puppet_module: 'tweaks'
tags: []
version: 1.0.0
