handler: puppet
id: 'apache'
input:
  ip:
    schema: str!
    value: ''
  ssh_key:
    schema: str!
    value: ''
  ssh_user:
    schema: str!
    value: ''
puppet_module: 'apache'
tags: []
version: 1.0.0
