handler: puppet
id: 'keystone'
input:
  ip:
    schema: str!
    value: ''
  ssh_key:
    schema: str!
    value: ''
  ssh_user:
    schema: str!
    value: ''
puppet_module: 'keystone'
tags: []
version: 1.0.0
